# Generated by Django 6.0.4 on 2026-04-20 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('FIXED', 'Fixed'), ('INSTALLMENT', 'Installment'), ('SUCCESS_FEE', 'Success Fee'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('win_probability', models.FloatField(default=1.0)),
                ('stage', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='firms.firm')),
            ],
        ),
        migrations.CreateModel(
            name='CasePaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_date', models.DateField()),
                ('probability', models.FloatField(default=1.0)),
                ('paid', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cases.case')),
            ],
        ),
    ]
